bind_addr = ":8080"
log_level = "debug"


#"postgres://postgres:1@localhost:5432/restapi_dev?sslmode=disable";
[store]
database_url = "postgres://postgres:1@localhost:5432/restapi_dev?sslmode=disable"