bind_addr = ":8080"
log_level = "debug"


#"postgres://postgres:1@localhost:5432/restapi_dev?sslmode=disable";
[store]
database_url = "host=localhost dbname=restapi_dev user=postgres password=1 sslmode=disable"